## what is numpy
- numpy ia fundamental packages for scientific computing in python
- numpy is a python library that provides a multidimensional array object, varies derived objects.
### what is numpy array
- an array is a grid of values and it contains information about the raw saya, how to locate an element, and hoe to interpret an element.
<img src="1d-Array.png" style="width:300px;"> <img src="2d.png" style="width:300px"> <img src="3d.webp" style="width:300px;">

## numpy vs python list
- Advantages of using Numpy Arrays over Python Lists
1. consumes less memory
2. fast as campare to python list.
3. convenient to use.


#### Installation Numpy
- pip install numpy
#### import numpy
- import numpy as np

In [2]:
import numpy as np
x = np.array([1,2,3,4,5])
print(type(x),x)
x = x*2
print(type(x),x)

<class 'numpy.ndarray'> [1 2 3 4 5]
<class 'numpy.ndarray'> [ 2  4  6  8 10]


In [3]:
y = [1,2,3,4,5]
print(type(y),y)
y=y*2
print(type(y),y)

<class 'list'> [1, 2, 3, 4, 5]
<class 'list'> [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [4]:
print(np.__version__)


2.3.4


### Multidimensional array

In [5]:
array1 = np.array(['A','B','C'])
print(f"Dimenstion of{array1} is {array1.ndim}")
print(array1.shape)
print("=======================================")
array2 = np.array([
    ['A','B','C'],
    ['D','E','F'],
    ['G','H','I']
])
print(f"Dimenstion of{array2} is {array2.ndim}")
print(array2.shape)
print("=======================================")
array3 = np.array([
    [['A','B','C'],['D','E','F'],['G','H','I']],
    [['J','K','L'],['M','N','O'],['P','Q','R']],
    [['S','T','U'],['R','W','X'],['Y','Z','  ']]
])
print(f"Dimenstion of{array3} is {array3.ndim}")
print(array3.shape)
print("=======================================")


Dimenstion of['A' 'B' 'C'] is 1
(3,)
Dimenstion of[['A' 'B' 'C']
 ['D' 'E' 'F']
 ['G' 'H' 'I']] is 2
(3, 3)
Dimenstion of[[['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['J' 'K' 'L']
  ['M' 'N' 'O']
  ['P' 'Q' 'R']]

 [['S' 'T' 'U']
  ['R' 'W' 'X']
  ['Y' 'Z' '  ']]] is 3
(3, 3, 3)


In [6]:

print(array3[0][0][0])
print(array3[0,0,0])
word = array3[0,0,0]+array3[1,2,0]+array3[1,2,0]+array3[1,0,2]+array3[0,1,1]
print(word)

A
A
APPLE


In [7]:
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
# array[strat:end:step] Subscript operator
print("Row")
print("array[0]:",array[0])
print( " ")
print("array[1]:",array[1])
print( " ")
print("array[2]:",array[2])
print( " ")
print("array[3]:",array[3])
print( " ")
print("array[0:3]:",array[0:3])
print( " ")
print("array[1:4]:",array[1:4])
print( " ")
print("array[2:]:",array[2:])
print( " ")
print("array[0:3:2]:",array[0:3:2])
print( " ")
print("array[ : :2]:",array[: : 2])
print( " ")
print("array[0:3:1]:",array[0:3:1])
print( " ")
print("array[ : :-1](Reverse):",array[: : -1])
print( " ")

Row
array[0]: [1 2 3 4]
 
array[1]: [5 6 7 8]
 
array[2]: [ 9 10 11 12]
 
array[3]: [13 14 15 16]
 
array[0:3]: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 
array[1:4]: [[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
 
array[2:]: [[ 9 10 11 12]
 [13 14 15 16]]
 
array[0:3:2]: [[ 1  2  3  4]
 [ 9 10 11 12]]
 
array[ : :2]: [[ 1  2  3  4]
 [ 9 10 11 12]]
 
array[0:3:1]: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 
array[ : :-1](Reverse): [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
 


In [8]:
print("Column")
print(array[:,1])#[2,,6,10,14]
print(array[: , -1]) # last column [4,8,12,16]
print(array[:,0:3]) # print first three column
print(array[:, 1::2])
print(array[:,::-1])

Column
[ 2  6 10 14]
[ 4  8 12 16]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [9]:
print(array[0:2,0:2])#[1,2,5,6]
print(array[2: , 2: ])#[11,12,15,16]
print(array[1:3,1:3])#[6,7,10,11]

[[1 2]
 [5 6]]
[[11 12]
 [15 16]]
[[ 6  7]
 [10 11]]


### Arithmetic Operaion

In [10]:
array = np.array([1,2,3,4])
print("Scaler Arithmetic")
print("Addition",array + 1)
print("Subtract",array - 2)
print("Multiplaction",array * 3)
print("Division",array/4)
print("Exponention",array ** 2)

Scaler Arithmetic
Addition [2 3 4 5]
Subtract [-1  0  1  2]
Multiplaction [ 3  6  9 12]
Division [0.25 0.5  0.75 1.  ]
Exponention [ 1  4  9 16]


In [11]:
array = np.array([1,2,3,4])
print("Vector Arithmetic")
print("Squre root:",np.sqrt(array))
array = np.array([1.32 ,2.56, 3.9, 4.09])
print("Round off: " , np.round(array))
print(np.pi)



Vector Arithmetic
Squre root: [1.         1.41421356 1.73205081 2.        ]
Round off:  [1. 3. 4. 4.]
3.141592653589793


### Exercise
assume array radii have radius of circle find area of circle /n
radii = np.array([1,2,3,4])

In [12]:
radii = np.array([1,2,3,4])
area = np.pi * radii ** 2
print(area)

[ 3.14159265 12.56637061 28.27433388 50.26548246]


### Element wise arithemetic

In [13]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])
print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
# print(array1 % array2)
print(array1 ** array2)



[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]


### Comparision Operator

In [14]:
score = np.array([91, 65, 32, 81, 55, 54, 25, 56, 100 ])
print(score == 100)
print(score >= 60)
print(score <= 60)

[False False False False False False False False  True]
[ True  True False  True False False False False  True]
[False False  True False  True  True  True  True False]


### Broadcasting
Broadcasting allows Numpy to perform opertaions on arrays with different shapes by virtually expanding demensions so they match the larger arrays's shape


the demensions have the same size

                OR

One of the dimension has a size of 1


In [19]:
array1 = np.array([[1, 2, 3, 4]])
array2 = np.array([[1], [2], [3],[4]])

print(array1.shape)
print(array2.shape)

print( array1 * array2)
array1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(array1.shape)
print(array2.shape)
# print( array1 * array2) error

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
(2, 4)
(4, 1)


In [21]:
array1 = np.array([
    [ 1, 2, 3,  4],
    [ 2,  4,  6,  8],
    [ 3,  6,  9, 12],
    [ 4,  8, 12, 16]
 ])
print(array1.shape)
print(array2.shape)
print(array1 * array2)

(4, 4)
(4, 1)
[[ 1  2  3  4]
 [ 4  8 12 16]
 [ 9 18 27 36]
 [16 32 48 64]]


In [24]:
array2 = np.array([[1, 5], [2, 6], [3, 7],[4, 8]])
print(array1.shape)
print(array2.shape)
# print(array1 * array2)Error

(4, 4)
(4, 2)


### Multiplication Table

In [25]:
array1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
array2 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])
print(array1.shape)
print(array2.shape)
print(array1 * array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
